;;; color-theme-ujelly.el : Mark Tran <mark.tran@gmail.com>

;;; Inspired by jellybeans: http://www.vim.org/scripts/script.php?script_id=2555.
(defvar ujelly-fg "#ffffff")
(defvar ujelly-bg "#000000")

(defvar ujelly-blue-0 "#8fbfdc")
(defvar ujelly-green-0 "#99ad6a")
(defvar ujelly-green-1 "#447799")
(defvar ujelly-grey-0 "#888888")
(defvar ujelly-grey-1 "#7f7f7f")
(defvar ujelly-grey-2 "#151515")
(defvar ujelly-orange-0 "#ffb964")
(defvar ujelly-purple-0 "#8197bf")
(defvar ujelly-purple-1 "#474e90")
(defvar ujelly-red-0 "#cf6a4c")
(defvar ujelly-red-1 "#363983")
(defvar ujelly-red-2 "#dd0093")
(defvar ujelly-yellow-0 "#fad07a")

(defun color-theme-ujelly ()
  "U Jelly? Theme"
  (interactive)
  (color-theme-install
   (append
    (list 'color-theme-ujelly
          `((background-mode . dark)
            (foreground-color . ,ujelly-fg)
            (border-color . ,ujelly-fg)
            (cursor-color . ,ujelly-grey-1))
          `(erc-notice-face ((t (:foreground ,ujelly-yellow-0))))
          `(erc-prompt-face ((t (:foreground ,ujelly-fg))))
          `(erc-timestamp-face ((t (:foreground ,ujelly-purple-0))))
          `(font-lock-builtin-face ((t (:foreground ,ujelly-blue-0))))
          `(font-lock-comment-face ((t (:italic t :foreground ,ujelly-grey-0))))
          `(font-lock-constant-face ((t (:foreground ,ujelly-green-1))))
          `(font-lock-doc-face ((t (:foreground ,ujelly-green-0))))
          `(font-lock-function-name-face ((t (:foreground ,ujelly-yellow-0))))
          `(font-lock-keyword-face ((t (:foreground ,ujelly-purple-0))))
          `(font-lock-preprocessor-face ((t (:foreground ,ujelly-fg))))
          `(font-lock-string-face ((t (:foreground ,ujelly-green-0))))
          `(font-lock-type-face ((t (:foreground ,ujelly-orange-0))))
          `(font-lock-variable-name-face ((t (:foreground ,ujelly-red-0))))
          `(font-lock-warning-face ((t (:foreground ,ujelly-red-2))))
          `(header-line ((t (:foreground ,ujelly-fg))))
          `(isearch ((t (:inverse-video t))))
          `(isearch-fail ((t (:background ,ujelly-red-2))))
          `(ido-first-match ((t (:foreground ,ujelly-yellow-0))))
          `(ido-only-match ((t (:foreground ,ujelly-green-0))))
          `(ido-subdir ((t (:foreground ,ujelly-grey-0))))
          `(lazy-highlight ((t (:foreground nil))))
          `(linum ((t (:italic t :foreground ,ujelly-grey-2))))
          `(magit-branch ((t (:foreground ,ujelly-red-2))))
          `(magit-diff-add ((t (:foreground ,ujelly-green-0))))
          `(magit-diff-del ((t (:foreground ,ujelly-red-0))))
          `(magit-diff-file-header ((t (:foreground ,ujelly-yellow-0))))
          `(magit-diff-hunk-header ((t (:foreground nil))))
          `(magit-item-highlight ((t (:background ,ujelly-grey-2))))
          `(magit-whitespace-warning-face ((t (:background ,ujelly-red-2))))
          `(minibuffer-prompt((t (:foreground ,ujelly-fg))))
          `(mode-line ((t (:foreground ,ujelly-fg))))
          `(mode-line-inactive ((t (:foreground ,ujelly-grey-2))))
          `(region ((t (:background ,ujelly-purple-1)))
          `(trailing-whitespace ((t (:background ,ujelly-red-2)))))))))
